packages:
  - "apps/*"
  - "packages/*"

blockExoticSubdeps: false
nodeLinker: hoisted

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
